### ISSUE TITLE
Socket Error - ECONREFUSED

### ISSUE THREAD

**Issue by tjosm** [cazala/coin-hive-stratum#80] opened 2017-12-03 04:11 UTC
I'm having few issues with websocket connection. I'm using wss with signed certificate. It starts with following lines on the error log,
```
2017-12-03 02:13: failed to send message to miner, websocket seems to be already closed not opened
2017-12-03 02:14: failed to send message to miner, websocket seems to be already closed not opened
2017-12-03 02:14: failed to send message to miner, websocket seems to be already closed not opened
2017-12-03 02:26: failed to send message to miner, websocket seems to be already closed not opened
2017-12-03 02:26: failed to send message to miner, websocket seems to be already closed not opened
2017-12-03 02:29: failed to send message to miner, websocket seems to be already closed not opened
```
this goes on for a while and then it starts to throw following,
```
2017-12-03 02:42: socket error (domain.com:3333) connect ECONNREFUSED 127.0.1.1:3333
2017-12-03 02:42: socket error (domain.com:3333) connect ECONNREFUSED 127.0.1.1:3333
2017-12-03 02:42: socket error (domain.com:3333) connect ECONNREFUSED 127.0.1.1:3333
2017-12-03 02:42: socket error (domain.com:3333) connect ECONNREFUSED 127.0.1.1:3333
2017-12-03 02:42: socket error (domain.com:3333) connect ECONNREFUSED 127.0.1.1:3333
```
I'm running node-xmr-proxy on port 3333 on the same server. And then within few seconds proxy goes down with following,

```
2017-12-03 02:42: socket error (domain.com:3333) connect ECONNREFUSED 127.0.1.1:3333
socket error (domain.com:3333) connect ECONNREFUSED 127.0.1.1:3333
2017-12-03 02:42: socket error (domain.com:3333) connect ECONNREFUSED 127.0.1.1:3333
socket error (domain.com:3333) connect ECONNREFUSED 127.0.1.1:3333
2017-12-03 02:42: socket error (domain.com:3333) connect ECONNREFUSED 127.0.1.1:3333
2017-12-03 02:42: socket error (domain.com:3333) connect ECONNREFUSED 127.0.1.1:3333
socket error (domain.com:3333) connect ECONNREFUSED 127.0.1.1:3333
2017-12-03 02:42: socket error (domain.com:3333) connect ECONNREFUSED 127.0.1.1:3333
2017-12-03 02:42: socket error (domain.com:3333) connect ECONNREFUSED 127.0.1.1:3333
socket error (domain.com:3333) connect ECONNREFUSED 127.0.1.1:3333
2017-12-03 02:42: socket error (domain.com:3333) connect ECONNREFUSED 127.0.1.1:3333
socket error (domain.com:3333) connect ECONNREFUSED 127.0.1.1:3333
```
This keeps happening every few hours and my hashrate drops. I was on a 512MB droplet with open file limit lifted. Then I created another 2 512MB droplets and tried round robin dns. each has both this proxy and xmr-node-proxy. But it still goes down every now and then. I'm not sure if I want to upgrade to 1GB droplets. Any advice will be appreciated.

PS my miners around 700 - 800

**Comment by cazala** [comment] 2017-12-03 06:48
it looks like the CHS proxies can't connect to your XNP proxy (on port 3333) maybe you are opening to many connections to the proxy? how many miners per connection have you setup?

**Comment by cazala** [comment] 2017-12-03 13:34
btw the first `failed to send message to miner, websocket seems to be already close` message shouldn't exist anymore, try using the latest version `v2.3.5`

**Comment by tjosm** [comment] 2017-12-03 15:17
I have set it to 100 miners per connection. Is it a good idea to increase this? I'll update now.

**Comment by tjosm** [comment] 2017-12-03 16:59
I've updated to v2.4.5 and increased miners per connection for 500. I currently have 3 connections to NXP at 127.0.1.1. So far so good.

Also I've upgraded my server to 2GB RAM and 2 Cores. The only this I see o the error log as of now are bunch of,

`2017-12-03 16:52: donation connection error (b215f608-0294-45f2-be76-f7d743e3205b) {"code":-1,"message":"Unauthenticated"}`

May be your address banned again?

**Comment by cazala** [comment] 2017-12-03 17:01
does it show up very often? donation connections should reconnect if that happens.. i ll check if the keepalive of the donation connections is working right. as far as i know i'm not banned again.

**Comment by tjosm** [comment] 2017-12-03 17:07
Yes, there are about 30 entries per minute. It's currently spamming the error log.

**Comment by cazala** [comment] 2017-12-03 18:25
i disabled the logging of that particular error `v2.5.0` for now until i make some tests to reproduce it. Donations have a reconnect and reauth mechanism for this type of errors.. but it shouldn't show up that often.

**Comment by tjosm** [comment] 2017-12-04 04:11
Thanks for the update. A new error came up,
`(node: 18849) warning: possible EventEmitter memory leak detected. 11 eba19c2a-0ae2-4c50-94a2-dfab6ead153d:accepted listeners added. Use emitter.setMaxListeners() to increase limit.`

I have about 1k miners rn

**Comment by tjosm** [comment] 2017-12-04 08:11
PM2 crashed and with it CHS and NXP. I think this is related to the error I mentioned above. It happens when CHS's memory usage reaches 200MB. Is there a way to increase this?

**Comment by cazala** [comment] 2017-12-04 11:39
yea, there was a memory leak (64adcda1c300ebb4667dad2ef5d731d135e7e4d7) it's fixed now in `v2.5.4`

**Comment by cazala** [comment] 2017-12-04 11:39
thanks for reporting!

**Comment by cazala** [comment] 2017-12-06 03:00
@tjosm can I ask how the proxy has been working for you since the last fixes?

**Comment by tjosm** [comment] 2017-12-08 14:38
Sorry about the delay @cazala 

The reported errors are certainly disappeared. But i'm seeing lots of these o the logs.
```
2017-12-08 14:23 +00:00: pool connection error (58ccc460-b266-4d79-bfd0-5969b2323b44): {"code":-1,"message":"Invalid job id"}
2017-12-08 14:23 +00:00: pool connection error (cd24d7e3-dc1a-415c-b350-f133ed4fc590): {"code":-1,"message":"Invalid job id"}
2017-12-08 14:24 +00:00: pool connection error (dcd93ba2-4459-4b91-87f3-9784ec21d3f7): {"code":-1,"message":"Invalid job id"}
2017-12-08 14:26 +00:00: pool connection error (932efac0-ad99-46a6-ace3-3f43979a5996): {"code":-1,"message":"Invalid job id"}
2017-12-08 14:26 +00:00: pool connection error (dd21771d-a468-4734-bbad-52e660391fb1): {"code":-1,"message":"Invalid job id"}
2017-12-08 14:27 +00:00: pool connection error (69c9e18d-92cd-493f-bb15-5a93b747ea6d): {"code":-1,"message":"Invalid job id"}
2017-12-08 14:27 +00:00: pool connection error (556ea958-08c7-49b5-83b0-b9b4aa478578): {"code":-1,"message":"Invalid job id"}
2017-12-08 14:28 +00:00: pool connection error (60696335-5a29-4f5c-82f7-d1e491803261): {"code":-1,"message":"Invalid job id"}
2017-12-08 14:29 +00:00: pool connection error (bb3e1686-49e6-400c-85a5-4a0dc880ba14): {"code":-1,"message":"Invalid job id"}
```
Not sure if this is a issue with NXP. I think this started to happen after I change max miners per connection to 1. It was 100 before. Snipa suggested that I try that. I'll slowly increase this and see what happens. I have more than 1k miners and connections atm. And it still crashes time to time.

**Comment by cazala** [comment] 2017-12-08 14:43
I have set up myself an XNP, and stopped using it for now, so far the best results (highest stable hashrate at the pool) I got were using the proxy connecting straight to the pool, with 100 miners per connection (still figuring out if 100 is the right number tho, but in my experience it's working better than 1 per connection). Just to let you know my results. I've been testing with users that have up to 1-1.5k miners per proxy instance.

**Comment by tjosm** [comment] 2017-12-08 14:54
Thanks for the info @cazala . Did you have any trouble on the pool side when connecting directly? I want to try that, but not sure if they will ban my address.

And also, you're welcome for testing on my server if needed. Just let me know.

**Comment by cazala** [comment] 2017-12-08 15:02
I've been talking to Snipa and M5M400, they told me the ban and DoS protection system they have is by IP when it has too many connections, but when multiplexing several miners thru a single connection this shouldn't be a problem. The time they banned my address was because of a spike in traffic by a user that was using https://coinhive-proxy.party which uses a tweaked old version of coin-hive-stratum, that used 1 connection per miner, (it was a spike of more than 10k connections coming from the same IP) but I don't think that having ~10 connections will get you in any trouble.

**Closed** 2017-12-10 18:24 UTC
